version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_1
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5434:5432"